version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nopass@1234
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:nopass@1234@db:5432/catalog_db
      PORT: 3006
    ports:
      - '3006:3006'
    command: sh -c "npx prisma migrate deploy && yarn start"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  db_data: